### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "NEW"
  , "developerSkillType": "FULL_STACK"
  , "experienceYears": "1"
  , "memberId": "Park11"
  , "name": "ParkJiHun"
  , "age" : 28
  , "sex" : "male"
  , "spec" : "8 projects of AI"
}
