### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "NEW"
  , "developerSkillType": "FRONT_END"
  , "experienceYears": "1"
  , "memberId": "seung11"
  , "name": "seunghye"
  , "age" : 27
  , "sex" : "female"
  , "spec" : "10 projects of Vision"
}
