### Send POST request with json body
POST http://localhost:8080/create-developer
Content-Type: application/json

{
  "developerLevel": "SENIOR"
  , "developerSkillType": "FRONT_END"
  , "experienceYears": "1"
  , "memberId": "ven25"
  , "name": "ven"
  , "age" : 25
}
